name: Deploy de la pagina
on:
  push:
    Branches:
      -main
jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: .
          clean: false
          single-commit: true
